### ISSUE TITLE
Initial distributions

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#100]
Generating initial distributions in the standard SixTrack like is now done in collimation version.

Necessary distributions:
- Load file
- Load file (normalized coordinates)
- Gaussian
- Pencil beam
- ...

Please use this issue to keep track of which distributions should be implemented + describe what it is and how it should be implemented.

The idea would be to have a new block in `fort.3`, which if present supersede/overwrite the distribution generated by the standard TRACK/INIT block.

**Comment by rdemaria** [comment]
Followed now in #111
