### ISSUE TITLE
Problems when building with GNU 10.2 for CircleCI checks

### ISSUE THREAD

**Issue by MarcoDAndrea** [SixTrack/SixTrack#1074]
Hello,

I have recently ran into some issues when running the CircleCI checks for a draft pull request. Essentially it was failing to build modules that I didn't touch, most likely because the version of the GNU compiler used by CircleCI has been updated.

I first had errors in the constants.f90 module related to the transfer function, such as:

/root/project/build/SixTrack_cmakesix_BUILD_TESTING_defaultcompiler_defaultbuildtype/constants.f90:61:52:
   61 |   real(kind=fPrec), parameter :: pi      = transfer(z'400921fb54442d18',1.0_fPrec)
      |                                                    1
Error: BOZ literal constant at (1) cannot be an actual argument to 'transfer'

Which could be solved by changing the corresponding lines to:

transfer(int(z'400921fb54442d18'),1.0_fPrec)

That solved this specific issue but I am now running into problems with the beam6d_fox.f90 module, which I report here:

/root/project/build/SixTrack_cmakesix_BUILD_TESTING_defaultcompiler_defaultbuildtype/beam6d_fox.f90:359:20:
  359 |          CALL DAALL(DUM     ,1*(13),'DUM       ',NORD,NVAR)
      |                    1
......
  829 |          CALL DAALL(A1      ,1,'A1        ',NORD,NVAR)
      |                    2
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/root/project/build/SixTrack_cmakesix_BUILD_TESTING_defaultcompiler_defaultbuildtype/beam6d_fox.f90:773:19:
  773 |         CALL DADAL(DUM     ,1*(13))
      |                   1
......
 1036 |         CALL DADAL(Z1      ,1)
      |                   2
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)

**Comment by rdemaria** [comment]
adding the option ` -fallow-argument-mismatch` to gfortran could solve the problem, but it is version 10 specific and needs to be carefully integrate in cmake

**Comment by JamesMolson** [comment]
Fixed in PR #1076
