### ISSUE TITLE
Collimation emittance is read from beam-beam block

### ISSUE THREAD

**Issue by KFubuki** [SixTrack/SixTrack#108]
The collimation block defines the opening of the collimators with respect to a certain emittance. This emittance is read from the beam-beam block, and the variables in the collimation block to specify the emittance are completely ignored. 

Since the collimator openings are usually given with respect to an emittance of 3.5 um, and the beam-beam block should be run with the correct emittance (2.5 um for HL-LHC), it is currently impossible to run beam-beam and collimation at the same time without completely changing the input of the collimation block. Furthermore, this fact is not documented, which can lead to many errors.

I suggest that we bring back to life the mute variables in the collimation block for emittances.

**Comment by kyrsjo** [comment]
Hi,

Can you try the kyrsjo/collimatEmittance branch?

**Comment by KFubuki** [comment]
No problem!

**Comment by kyrsjo** [comment]
This is being handled in PR #109

**Comment by kyrsjo** [comment]
Fixed!
