### ISSUE TITLE
Remove "Comments as version control"

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#114]
* Delete all lines with "!hrXX" - these are just new parenthesis, and the old expressions are often wrong; this should remove about 3000 unnecessary lines

More?

To be done in a separate branch...

**Comment by JamesMolson** [comment]
sed -i -e '/^\!hr[0-1][0-9].*/d' sixtrack.s

**Comment by kyrsjo** [comment]
Also kill `!hhr` `!hrr` lines

**Comment by rdemaria** [comment]
I think we can remove them in the main branch as well, I just want to be sure that there is no other use about those lines, like automatic tools relying on that...

**Comment by kyrsjo** [comment]
No tools that I know about relies on these... So unless you have any?

I'll ping Eric to check that he is also OK with it.

**Comment by kyrsjo** [comment]
Eric is OK with it, as long as it comes with TWO version bumps. I guess we're due for one anyway... I'll comment more on the general strategy in #119 

> Hi Kyrre, these comments indicate everywhere Harry Renshall
> inserted parentheses for unique order of evaluation.
> They are definitely of historic interest. I guess it is OK to
> delete now as long as we keep the new version and the previous version
> with parentheses for comparison. It would certainly reduce the number
> of lines in sixtrack.s (and lielib.s etc). In other words this should be the
> ONLY change between two consecutive versions apart from the Version Number.
> Eric.
>

**Comment by JamesMolson** [comment]
A lot of the collimation code is guilty of this as well. I'll have a scrub of that in the future when I have time.

**Comment by kyrsjo** [comment]
Partially fixed in #117 . Keeping open until also fixed in collimation.

**Comment by kyrsjo** [comment]
I think we have the go ahead from the collimation team? @rbruce1 @amereghe ?

**Comment by rdemaria** [comment]
@amereghe, can you comment?

**Comment by amereghe** [comment]
I would say 'go ahead'

**Comment by vkbo** [comment]
Still partially an issue in collimation, including in some of the recently added code!

The `!hrXX` etc comments are kill-on-sight. I've removed a lot, but we may just do a global replace of them.

**Comment by vkbo** [comment]
All `!hrXX` type comments removed in PR #944

**Comment by JamesMolson** [comment]
done I guess

**Comment by vkbo** [comment]
Yeah, think I got the rest when I went through the collimation module.
