### ISSUE TITLE
Cleanup CRLIBM

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#115]
Move the "liberic" files out of crlibm folder, remove fpucontrol.h, possibly get new CRLIBM. Merge before changing CRLIBM version!

**Comment by JamesMolson** [comment]
For future reference: http://lipforge.ens-lyon.fr/www/crlibm/start.html

**Comment by kyrsjo** [comment]
Hmm.. Which files are actually from crlibm and which are from liberic?

**Comment by kyrsjo** [comment]
Fixed in #163 (except for the "Update to newest version") part.
