### ISSUE TITLE
CRLIBM issues: Compile with SSE2 support, drop x87

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#12]
The function cos_rn() returns different results for different the same and large argument when compiled with different versions of GCC.

This can be avoided by using SSE2 math instead of x87, as this produces consistent results (consistent across compiler versions, and for gcc version 4.4.7 x87 and SSE agrees).

For gcc (crlibm), this is done by using the compilation flags "-mfpmath=sse -msse2".

**Comment by kyrsjo** [comment]
@ldeniau @ericmcintosh

**Comment by ldeniau** [comment]
Hi Kyrre,

Please use my cern.ch email address. gmail.com is my private emails.

cheers,
Laurent.

**Comment by kyrsjo** [comment]
Hi Laurent,

I just tagged your username on GitHub, which then sent you the email. Do you have another github handle?

By the way: Apparently (from reading the email I forwarded you again) I did try to reduce the amount of code to just what was needed, but then the problem disappeared.

Cheers,
Kyrre

On 18 Sep 2015, at 14:57, Laurent Deniau <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Kyrre,

Please use my cern.ch<http://cern.ch> email address. gmail.com<http://gmail.com> is my private emails.

cheers,
Laurent.

**Comment by ldeniau** [comment]
Hi Kyrre,

On Sep 18, 2015, at 3:03 PM, Kyrre Ness Sjøbæk <notifications@github.com> wrote:

> Hi Laurent,
> 
> I just tagged your username on GitHub, which then sent you the email. Do you have another github handle?
> 
> By the way: Apparently (from reading the email I forwarded you again) I did try to reduce the amount of code to just what was needed, but then the problem disappeared.

Interesting, it might be an hint that the problem is elsewhere…

Cheers,
Laurent.

> 
> Cheers,
> Kyrre
>

**Comment by kyrsjo** [comment]
Hi Laurent,

As I said: I’ve already spent too much time on this, and given that (1) using SSE2 “fixes” (or at least masks it, if it is a GCC change) it and (2) new CRLIBM is on the way, I decided to stop trying to fix this problem. Especially since reporting floating point reproducibility issues to GCC seems to be very hard and fixing them is not something they seem to have much interest in.

However, it is still something to be aware of, and a reminder that the very long SixTest runs are sometimes useful.

Cheers,
Kyrre

On 18 Sep 2015, at 15:08, Laurent Deniau <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Kyrre,

On Sep 18, 2015, at 3:03 PM, Kyrre Ness Sjøbæk <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hi Laurent,
>
> I just tagged your username on GitHub, which then sent you the email. Do you have another github handle?
>
> By the way: Apparently (from reading the email I forwarded you again) I did try to reduce the amount of code to just what was needed, but then the problem disappeared.

Interesting, it might be an hint that the problem is elsewhere…

Cheers,
Laurent.

>
> Cheers,
> Kyrre
>

**Comment by kyrsjo** [comment]
Fixed by pull #19
