### ISSUE TITLE
Collimation output - field length in tracks2.dat too short for FCC

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#120]
Email from Maria Fiascaris ( @mfiascar )

> Dear Kyrre,
> 
> I found a bug in sixtrack, in the collimation routine when writing out tracks2.dat. The problem only occurs with FCC if the ring lenght is > 100 km.
> Basically the number of digits for the s position was not enough and when reaching s=100000.0, **** was written out instead of the s position. Then BeamLossPattern obviously exits when it reaches that line and only a small fraction of the tracks2.dat is read, with the user not even realizing (I only noticed because my loss maps were strangely too cleaned!).
> 
> I fixed that simply by modifying in sixtrack.s all instances of
> 
> write(38,'(1x,i8,1x,i4,1x,f8.2,4(1x,e11.5),1x,e11.3,1x,i4)')   &
> 
> into
> 
> write(38,'(1x,i8,1x,i4,1x,f10.2,4(1x,e11.5),1x,e11.3,1x,i4)') &
> 
> Could you please make this bug fix on the trunk version in git?
> I have already changed job and I don't have much time for collimation stuff. My sixtrack version is not up to date with the trunk in git, and as I am trying to get done other urgent things, I though you would be probably faster at doing it yourself.
> Let me know if have any question.
> 
> Thanks!
> cheers,
> Maria

**Comment by kyrsjo** [comment]
Any impact on BeamLossPattern?

**Comment by JamesMolson** [comment]
https://svnweb.cern.ch/cern/wsvn/collsoft/SixTrack_material/Utilities/Post_SixTrack/trunk/BeamLossPattern.cpp

Line 232:

in>>n_t>>n_tu>>s_t>>x_t>>xp_t>>y_t>>yp_t>>en_t>>n_h;

Field size/white space does not matter in BLP.

**Comment by mfiascar** [comment]
Hi Kyrre,
thanks, nothing to be changed in Beam Loss Pattern.
cheers,
Maria

**Comment by kyrsjo** [comment]
Fixed! Pull request #124
