### ISSUE TITLE
Cannot build with nagfor

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#123]
Loading nagfor like `source /afs/cern.ch/sw/fortran/nag/usenag.bash 6.0`, I have two issues blocking the build:
1. If I *don't* use DATAMODS, `datamods.f` is an empty file containing only a comment. Nagfor doesn't like that...
2. Switching DATAMODS on, this part works, but it blows up when building PLATO, with the error message
```
Error: plato_seq.f, line 1093: Implicit type for DCMPLX
Error: plato_seq.f, line 1093: Implicit type for DFLOAT
```
There are also infinite warnings about unused variables (CRLIBM functions etc.).

**Comment by JamesMolson** [comment]
We also have -maxcontin=60 which it complains about.

From the manual:

-maxcontin=N
Increase the limit on the number of continuation lines from 255 to N.  This option will not decrease the limit below the standard number.


Setting it to 60 is pointless.

**Comment by kyrsjo** [comment]
Agreed :)

**Comment by JamesMolson** [comment]
So, DFLOAT and DCMPLX seem to be extensions.
My test dies on DFLOAT but says
"plato_seq.f, line 134: DCMPLX intrinsic procedure"
for DCMPLX.

DFLOAT seems to convert an integer to a double.

There is a standard function DBLE() that does the same thing, but converts more data types, so this should probably be used instead.

**Comment by JamesMolson** [comment]
so:

-dcfuns   Enable recognition of non-standard double precision complex intrinsic functions.  These act as specific versions of the standard generic intrinsics as follows:

                 Specific       Equivalent Fortran 90/95 Generic Intrinsic

                 CDABS(A)       ABS(A)

                 DCMPLX(X,Y)    CMPLX(X,Y,KIND=KIND(0d0))

                 DCONJG(Z)      CONJG(Z)

                 DIMAG(Z)       AIMAG(Z)

                 DREAL(Z)       REAL(Z) or DBLE(Z)


That needs turning back on.
Datamods needs enabling
then DFLOAT needs swapping for DBLE, and it builds okay.

I have not run the test suite yet.

**Comment by kyrsjo** [comment]
For non-standard functions, see #134

**Comment by JamesMolson** [comment]
I guess if we don't enable datamods then don't include datamods.f as a source file. Simple!

**Comment by kyrsjo** [comment]
Now we can build with nagfor (except FMA crashes, see #138 ), so I'll close this one.
