### ISSUE TITLE
Rank mismatch complilation warnings

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#13]
Problem:
gfortran gives a lot of warnings when compiling "dabnews.f" and "lielib.f". This may not be a real problem, but the excessive output may mask real problems by drowning them.

> gfortran -c -frecord-marker=4 -O4 -m32 -g -fno-second-underscore -funroll-loops dabnews.f
> dabnews.f:376.17:
> 
> ```
>   call daall(iall,1,'$$UNPACK$$',nomax,nvmax)                       
>              1
> ```
> 
> Warning: Rank mismatch in argument 'ic' at (1) (rank-1 and scalar)
> dabnews.f:383.17:
> 
> ```
>   call daall(iall,1,aa,nomax,nvmax)                                 
>              1
> ```

(etc. -- the output is here cropped)

The code for these files are found in dabnew.s and lielib.s, and are preprocesses through the astuce masks lielib.ast and dabnews.ast.

**Comment by rdemaria** [comment]
Is it a new issue, or has always been there?

**Comment by kyrsjo** [comment]
It has been there as long as I've worked with SixTrack.

**Comment by kyrsjo** [comment]
Fixed in #118 by James Molson!
