### ISSUE TITLE
Cannot build with lf95

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#136]

**Comment by JamesMolson** [comment]
It seem the version of lf95 on lxplus doesn't know about anything existing after fortran 95 and any processors after the pentium 4.

**Comment by kyrsjo** [comment]
Personally, I would vote for dropping this compiler...

**Comment by kyrsjo** [comment]
Nobody at the meeting protested dropping it. So dropped it is.

This also means we can (cautiously) use some Fortran 2003 features like "retrieving the standard output unit" and "reading the command line arguments".

**Comment by kyrsjo** [comment]
By the way: It seems that "round" should be supported now?
http://fortranwiki.org/fortran/show/Fortran+2003+status
