### ISSUE TITLE
FMA test fails on some compilers

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#138]
There seems to be some problems with the FMA module, as it fails when compiled with certain compilers.

With nagfor it crashes - see #134 for the error message - the offending line being:
```
                eps123_min(m)=minval(epsnxyzv(l,1:fma_nturn(i),m),      &
     &fma_nturn(i))      ! minimum emittance
```

With newer versions of GCC (which are also 64 bit), TUNEFFTI gives slightly different tunes. @JamesMolson  is investigating this. I checked, and there are no parentheses missing or anything like that.

Miriam: Could you please give a quick description of what this line is supposed to be doing?

**Comment by JamesMolson** [comment]
This test as 64bit works on my desktop. It fails as 64bit on lxplus. It passes on lxplus as 32bit.

fort.10, fort.90 always are good, all the DUMP files are good, it is just the fma_sixtrack in extra_checks.txt that has a few bits off.

**Comment by kyrsjo** [comment]
It is very interesting that it works in 64-bit on your desktop, but not on LxPlus. Which compilers? Any system-provided libraries that we link with?

**Comment by kyrsjo** [comment]
Note: I checked `plato_seq.s` for missing paranthesis. I did not recheck the relevant parts of `sixtrack.s`.

**Comment by mfittere** [comment]
for the minval, maybe we have to add the dimension of the array:
[minval](https://gcc.gnu.org/onlinedocs/gfortran/MINVAL.html)

Can you try?

**Comment by mfittere** [comment]
i = fma file = number of lines in FMA block
l = particle number
m = mode
1:fma_nturn(i) = number of turns used for the FMA analysis

e.g. if you do the FMA for fma_nturn(i)=10000 turns, the array epsnxyzv(l,1:fma_nturn(i),m) should have dimension 10 000.

Also looking at the line:
```
epsnxyzv(l,1:fma_nturn(i),m),      &
     &fma_nturn(i))
```
the right dimension of the array is given, so this should be correct!

Any other ideas?

**Comment by JamesMolson** [comment]
> e.g. if you do the FMA for fma_nturn(i)=10000 turns, the array epsnxyzv(l,1:fma_nturn(i),m) should have dimension 10 000.


uh. No? It has a length of 10000, not 10000 dimensions...

It just runs from 1 to fma_nturn(i), so a 1 dimensional line.

**Comment by kyrsjo** [comment]
James is right, it's dimension as in which index to run along. Agreed that the terminology is somewhat confusing, but it is quite standard; I met it first in numpy.

**Comment by mfittere** [comment]
I am not so sure. Read this for example:

https://web.stanford.edu/class/me200c/tutorial_90/07_arrays.html

In case of 1d arrays, if my array has a length of 10, the dimension is 
10. For 2d arrays it would be e.g. for a 2x5 array with 10 entries, it 
would be (2,5). So I think the code is correct???

Miriam

**Comment by JamesMolson** [comment]
> In case of 1d arrays, if my array has a length of 10, the dimension is 10. For 2d arrays it would be e.g. for a 2x5 array with 10 entries, it would be (2,5). So I think the code is correct???

No. The 1d array has dimension 1, the 2d array has dimension 2, etc...

It even says in the the document you linked to:
> The maximum limit on the rank (the number of dimensions) of an array is 7. 

Again, see the documentation here:

https://software.intel.com/en-us/node/693269

the dim argument specifies in which direction you want to do the minval operation.

**Comment by mfittere** [comment]
you are right! So instead of fma_nturn(i) it should then be 1.

Miriam

**Comment by mfittere** [comment]
So James is right. It should be dimension 1 and this is a bug.

**Comment by JamesMolson** [comment]
Anyway, last night I changed it and re-built with nagfor.

The fma test now runs okay, but still did not match the output for TUNEFFTI.

I will look into building with make_six as 64bit and 32 bit and see if that is what kills it.


The errors only happen in TUNEFFTI though.

**Comment by mfittere** [comment]
thanks a lot!!!!
And you got the same results for the IP*_DUMP* and *NORM* files? Just double checking ...

**Comment by JamesMolson** [comment]
Yes. Except on nagfor the headers are different on some files:

```
--- IP2_DUMP_1	2016-12-08 03:34:20.000000001 +0100
+++ IP2_DUMP_1.canonical	2016-11-24 17:56:56.000000001 +0100
@@ -1,5 +1,5 @@
- # DUMP format #2, bez=ip2             , number of particles= 60
- # dump period= 1 , first turn= 1 , last turn= 4096
+ # DUMP format #2, bez=ip2             , number of particles=          60
+ # dump period=           1 , first turn=           1 , last turn=        4096
```

Note the different spacing. The actual contents of the file are the same.

fma_sixtrack:
```
           IP2_DUMP_1             TUNEFFTI        1  3.100555728E-01  3.198639515E-01  2.159226953E-03  1.866934046E-03  1.275595999E-04  6.934113813E-08  1.901995730E-03  1.433888950E-04  6.934230266E-02  1.885106500E-03  1.341783182E-04  3.441146343E-02  1.874843957E-03  1.347157193E-04  6.934113813E-08  2.924244548E-03  1.819842148E-02 -1.570791959E+00
```

fma_sixtrack.canonical:
```
           IP2_DUMP_1             TUNEFFTI        1  3.100556135E-01  3.198639154E-01  2.159226919E-03  1.866934046E-03  1.275595999E-04  6.934113813E-08  1.901995730E-03  1.433888950E-04  6.934230266E-02  1.885106500E-03  1.341783182E-04  3.441146343E-02  1.874843957E-03  1.347157193E-04  6.934113813E-08  2.924244548E-03  1.819842148E-02 -1.570791959E+00
```

and so on...


Only q1,q2,q3 are different.

**Comment by mfittere** [comment]
if the spacing is a bit different it doesn't matter. And from what you posted only the timestamp in the header is different, so all looks fine!

Thanks a lot for checking all this and finding the bug!

**Comment by JamesMolson** [comment]
That is just the output from diff, ignore the first 3 lines.

In the code we have:
```
                   write(dumpunit(i),*)
     &  '# DUMP format #2, bez=', bez(i), ', number of particles=', napx
                   write(dumpunit(i),fmt=*)
     &  '# dump period=', ndumpt(i), ', first turn=', dumpfirst(i),
     &  ', last turn=', dumplast(i)
```

I guess since you do write(dumpunit(i),*) and don't specify a format string then the output format isn't exactly specified, and thus we get extra spaces from nagfor which I would imagine is being safe and putting that in, and due to this the diff and thus the test will fail.

For the TUNEFFTI problem I'll have a look at what kyrre has done in #143

**Comment by mfittere** [comment]
Thanks! Very good!

**Comment by kyrsjo** [comment]
Yeah, I fixed the DIMENSIONS problem there (the first commit), and I totally broke tuneffti and tunefft in the 2nd... Now I get different results in nagfor and gfortran, which are both different from canonical! Tune = 9 or NaN!

So yeah, something is wrong here...

For the DUMP headers, I will simply put a FORMAT there to make sure it is the same as the current canonicals.

**Comment by kyrsjo** [comment]
Please see #143 .

The DUMP stuff and minval/maxval problems are fixed, as is the bad tunes. Furthermore, I converted PLATO to fully double-precission; I discussed with Eric and he mentioned that double->single and single->double conversions are not really consistent... This turned out to be the problem. Now it works 100%.

For #144; It was not necessary (and it's a pain to fix).

Miriam; After merging this you may want to re-visit a few of the bugs that are linked from #79 !
