### ISSUE TITLE
Documentation fort.3

### ISSUE THREAD

**Issue by androula** [SixTrack/SixTrack#150]
Would be good if in the documentation it was mentioned explicitly that SPECIAL ELEMENTS go in fort.3

**Comment by kyrsjo** [comment]
Please make a pull request :)On Dec 16, 2016 16:40, androula <notifications@github.com> wrote:Would be good if in the documentation it was mentioned explicitly that SPECIAL ELEMENTS go in fort.3

**Comment by kyrsjo** [comment]
FYI, everything goes into `fort.3` - unless you put `GEOM` at the top of fort.3 which causes it to read the machine geometry from `fort.2`. See Section 3.3.3 "Program version".

**Comment by androula** [comment]
Thanks! Done!

**Comment by kyrsjo** [comment]
#152

**Comment by kyrsjo** [comment]
Hi, give me a few minutes to finish the FMA fixes and I can show you how to setup a proper pull request!

**Comment by JamesMolson** [comment]
Fixed with #155 ?

**Comment by kyrsjo** [comment]
Fixed with #155.
