### ISSUE TITLE
Extra tab in fort.2 spoils the code

### ISSUE THREAD

**Issue by androula** [SixTrack/SixTrack#153]
Just an extra tab (visible with :set list) in fort.2 can make the code not work. Error message: 
++++++++++++++++++++++++
         +++++ERROR DETECTED+++++
         ++++++++++++++++++++++++
         RUN TERMINATED ABNORMALLY !!!

         UNKNOWN BLOCK NAME OR INSERTION NAME : mymmq.1          IN THE STRUCTURE INPUT

     
mymmq.1 is not unknown, it just has an extra tab by its name

**Comment by kyrsjo** [comment]
An easy fix for this would be to add quotes in the error message, i.e. it would be
```
     UNKNOWN BLOCK NAME OR INSERTION NAME : 'mymmq.1    '      IN THE STRUCTURE INPUT
```
