### ISSUE TITLE
Initialization of elens in initialize_element

### ISSUE THREAD

**Issue by mfittere** [SixTrack/SixTrack#156]
Elens is missing in initialize_element. Was it removed or never implemented?

**Comment by kyrsjo** [comment]
Oops. I guess never implemented?On Dec 23, 2016 9:05 PM, mfittere <notifications@github.com> wrote:Elens is missing in initialize_element. Was it removed or never implemented?

**Comment by mfittere** [comment]
I can fix it once I am done with the wire

**Comment by kyrsjo** [comment]
Great, thanks :)

**Comment by mfittere** [comment]
I fixed it. It should come with the new wire merge.

**Comment by mfittere** [comment]
fine

**Comment by mfittere** [comment]
Sth. else: there is no elensidealthin6d_DYNK**in** folder?

**Comment by kyrsjo** [comment]
Good spot.

I'm not really sure why we really need the XXX*in* folders; removing them would reduce the clutter a bit. I'll ask Eric...

Cheers,
Kyrre

**Comment by mfittere** [comment]
I was always wondering why we need them. Thanks for asking!

Miriam

**Comment by kyrsjo** [comment]
They are now deleted - see PR #165 !

**Comment by kyrsjo** [comment]
This was fixed in the patch merged in PR #174
