### ISSUE TITLE
TUNEFFTI giving Q3=NAN in fma_sixtrack

### ISSUE THREAD

**Issue by androula** [SixTrack/SixTrack#159]
Running with SixTrack_4545_crlibm_fast_tilt_cmake_gfortran_static_64:

-when using TUNEFFTI in fort.3 then Q3=NAN in fma_sixtrack
-with TUNEFIT method Q3 is non-NAN

**Comment by mfittere** [comment]
Do you get the correct value for Q3 with TUNEFIT? Is this the case with cavity voltage zero you submitted in [#160](https://github.com/SixTrack/SixTrack/issues/160)? If it is with voltage 0 you don't have correct synchrotron motion and thus no real tune. I would guess that you get sth. with the TUNEFIT as it is a fit, while the FFT fails. 

Some checks:
1. Plot the trajectories (z,dp) using the dump files?
2. Plot the normalized phase space using the NORM_DUMP files. The format is given in the header (columns `nsig[1.e-3 sqrt(m)] ndp/p[1.e-3 sqrt(m)]`)

**Comment by vkbo** [comment]
The NAN issues in FMA were solved some time ago. They were caused by some issues in PLATO_SEQ where some indices sometimes ran out of bounds. Additional checks have been added to handle this.
