### ISSUE TITLE
CMake/CTest issues and support.

### ISSUE THREAD

**Issue by JamesMolson** [SixTrack/SixTrack#161]
Things to work on currently:

- BOINC builds.
- Documentation.
- General dashboard submission scripts.
- Make CR testing a bit nicer.
- DA build test format.

Also, do people have a common list of build options that should be combined for testing.

Getting every possible combination is a bit excessive.

**Comment by JamesMolson** [comment]
cmake_six fails on FreeBSD:

```
$ ./cmake_six
Welcome to cmake_six, camouflaging cmake and make inside the same interface as make_six !
For help, run 'cmake_six help'


Running 'gawk -f beauty/count.awk sixtrack.s' to check sanity of astuce directives in sixtrack.s:
Maximum nesting level=4
--> count.awk completed without errors.
Running 'gawk -f beauty/check_astuce_ifs.awk sixtrack.s' to check sanity of astuce directives in sixtrack.s:
--> check_astuce_ifs.awk completed without errors.
Running 'gawk -f beauty/count.awk plato_seq.s' to check sanity of astuce directives in plato_seq.s:
Maximum nesting level=1
--> count.awk completed without errors.
Running 'gawk -f beauty/check_astuce_ifs.awk plato_seq.s' to check sanity of astuce directives in sixtrack.s:
--> check_astuce_ifs.awk completed without errors.

options_ON  =
options_OFF =
NAME= 'SixTrack_cmakesix_defaultcompiler_defaultbuildtype'
CMAKE options = ' '

./cmake_six: line 275: /dev/fd/62: Operation not supported

ERROR in CMAKE;
Most likely you specified a bad argument!
Please run cmake_six help

```

**Comment by kyrsjo** [comment]
See also #191

**Comment by rdemaria** [comment]
Any progress here?

**Comment by kyrsjo** [comment]
CR tests does work now. I don't know about the docs, I wrote some in the build manual, other than that it's mainly word-of-mouth.

DA I don't think is really tested...

BOINC testing I think I fixed.

There are still a few issues with the test-self-test scripts, in that they may try to write to the same folders and/or to the source folders, causing spurious crashes.

**Comment by vkbo** [comment]
The CR + BOINC combination is now well covered, and we have two operational DA tests. I think this issue can be closed. It's a bit vague anyway.
