### ISSUE TITLE
RIPP block NOT VALID

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#182]
If RIPP block is present in `fort.3`, currently it just prints a warning and continues tracking. It should STOP and tell the user how to convert the fort.3 (there is a Python script).

**Comment by kyrsjo** [comment]
This being fixed would have made #190 a lot easier to understand :)

**Comment by JamesMolson** [comment]
And the current BOINC mac issue!

**Comment by kyrsjo** [comment]
Here "the current BOINC mac issue" refers to the pushing of sixtrack 4.5.30, which was just skipping RIPP blocks, to macs on BOINC that were expecting 4.5.17-style input (no DYNK, supports RIPP). Whoopsie.
