### ISSUE TITLE
Canonicals missing for test `elensidealthin6d_DYNK`

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#189]
All canonicals seems to be missing for this test.

Miriam: Could you please checkout the newest master on Linux and create a new branch from there, do a standard build (just run ./cmake_six without any arguments - it should give you a gfortran build), run this test with SixTest (run_pro), rename the fort.10 etc. + your extra_checks to .canonical as usual, commit the files, and make a PR? This should be a quick fix...

If you have canonicals already, could you please just commit these to a new branch off off master?

Cheers,
Kyrre

**Comment by kyrsjo** [comment]
@JamesMolson : I'm surprised that ctest didn't catch this...

**Comment by mfittere** [comment]
I didn't write this test. It was I think Josch and you. I can check the e-lens part, but I don't know what the dynk part is supposed to do. Do you remember?

**Comment by kyrsjo** [comment]
Hmm. I'll check. I can also just add canonicals myself, I was just thinking that maybe you had them lying around.

@jfwagner , do you remember ?

**Comment by mfittere** [comment]
I am writing Josch a mail.
