### ISSUE TITLE
Online aperture check

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#217]
Loading an aperture model and checking that the particles stays within the defined aperture during tracking.

This eliminates the need for tracks2.dat in collimation, and simplifies the postprocessing. It is a prerequisite for #216 .

**Comment by JamesMolson** [comment]
Now implemented in dev.

**Comment by amereghe** [comment]
not finished, yet, and not yet ready for release.

**Comment by amereghe** [comment]
implemented and compatible with BOINC since [v5.1.0](https://github.com/SixTrack/SixTrack/tree/v5.1.0)
Closing the issue
