### ISSUE TITLE
crabamp test

### ISSUE THREAD

**Issue by JamesMolson** [SixTrack/SixTrack#219]
The normalized emittance is set to 5.32894e+09 ? when the units are in um rad.

This seems.... high. Surely it should be ~3.75?

**Comment by kyrsjo** [comment]
The BEAM block reads:
```
BEAM
  0.0000e+00   5.32894e+09   5.32894e+09  0.0000e+00  0.0000e+00  1  0
NEXT
```

Where item 2 and 3 are supposed to be the normalized emittance. Where did this number come from?

**Comment by JamesMolson** [comment]
The "exact" test:
```
BEAM
0.0000e+00   1.24731e+06   1.24731e+06  0.0000e+00  0.0000e+00  1  0
NEXT
```

I have no idea where that could come from either.

**Comment by JamesMolson** [comment]
thick6dsingles:

```
BEAM
0.0000e+00   1.24731e+06   1.24731e+06  0.0000e+00  0.0000e+00  1  0
NEXT
```

**Comment by rdemaria** [comment]
shall we fix this? If there is no beam-beam, physics will not affected

**Comment by rdemaria** [comment]
No test called crabamp anymore
