### ISSUE TITLE
Put the manual on the web in a better way

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#227]
Write a readme for how to put things on http://sixtrack.web.cern.ch/SixTrack/ and delete the PDFs from the repository.

**Comment by rdemaria** [comment]
Where do you want the readme?

**Comment by kyrsjo** [comment]
Which readme?

**Comment by vkbo** [comment]
Not sure what the issue is, but there is a new website with HTML and PDF manuals. I'm closing this.
