### ISSUE TITLE
Quicktest

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#23]
Quicktest: An easy-to-use testing system.

Contents of the QuickTest folder:
- Script to run QuickTest: Optional arguments: List of path <name>/reference to computational unit.  Will make(_six) binaries using the current working copy, create `DateTime-SHA1` folders, copy binary+input+canonical there, then run `run_test` (or default test if this is not in place: Just run the binary+full diff vs. provided canonicals). Do not accept if there are uncommited changes.
- Folders for tests: Contents:
  - `input` folder:
    - Contains the fort.2, fort.3, CollDB etc.
    - CR/Testing script (standard name: "run_test") to return no error  when run and output files are copied
  - Reference folders: named as sorted list of options such as `reference_option1_option2_etc`. Contents
    - Canonicals: Containing a full copy of all (relevant) outputs
  - `DateTime-SHA1`: Binary+output from running the binary produce my test system.
  - Readme? Describe scenario few lines + author + which SHA1 was used for canonicals.

**Comment by kyrsjo** [comment]
See also:
https://github.com/kyrsjo/SixTrack/commit/5c487e4a9c1e7bb9654e88124ca9134af678510f
https://github.com/kyrsjo/SixTrack/commit/cd4491e08b779243a4e65106038bda8d351157b7
https://github.com/kyrsjo/SixTrack/commit/50fa0a6be0ba2a077be19828e08abfd372ddec6d
https://github.com/kyrsjo/SixTrack/commit/07ee2cb13834807050a119659c204c0f7899ab6b
https://github.com/kyrsjo/SixTrack/commit/49b128023f1f623e2638e5e2598aace36e605ee2

This may be the beginning of a pretty general testing system.

**Comment by kyrsjo** [comment]
This will probably be superseeded by the CTest testing system in #107 ? Linking it in case this issue contains valuable information...

**Comment by rdemaria** [comment]
I hope we could have the 'coverity' tool to  assess our test coverage...

**Comment by kyrsjo** [comment]
There is CDash!

http://abp-cdash.web.cern.ch/abp-cdash/

**Comment by rdemaria** [comment]
I don't see sixtrack :-)

**Comment by kyrsjo** [comment]
Yngve is control! Calling @Eothred ...

**Comment by Eothred** [comment]
Hi, yes I am still admin of that server, happy to grant access. I also gave the login info to a few people before I left but I'm not sure if anyone took note of it :)

I'll send info by e-mail

**Comment by Eothred** [comment]
https://abp-cdash.web.cern.ch/abp-cdash/index.php?project=SixTrack Enjoy!

**Comment by JamesMolson** [comment]
Could you update it to the current cdash version?

And I just tried to register and that didn't seem to work - sent me an email but the link it contained was broken.

**Comment by JamesMolson** [comment]
In addition, I did just try a "test" test, and was able to submit as you can see.

**Comment by Eothred** [comment]
Hmm, this server was used by primarily myself, so maybe some particularities are not working 100%. I registered you now and you should have gotten an e-mail. I will give your account full admin access to the server so you can fix whatever needs fixing.

**Comment by kyrsjo** [comment]
OK, I would be very happy if James could handle this. I also sent an email to possible users, I did not hear anything yet. If James and Yngve could coordinate, this would be absolutely great!

**Comment by JamesMolson** [comment]
I tried to login with my email and it says I do not exist. I didn't get any new emails either :)

Perhaps @kyrsjo could try as well?

**Comment by JamesMolson** [comment]
Also there is this: https://blog.kitware.com/cdash-integration-with-github/

**Comment by JamesMolson** [comment]
Okay, we both have admin access and can submit tests now.

A possible next step: https://cmake.org/Wiki/CMake_Scripting_Of_CTest

**Comment by kyrsjo** [comment]
We've got ctest -> quicktest is no longer needed.
