### ISSUE TITLE
No collimation examples new fix

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#25]
See af71c39

**Comment by rdemaria** [comment]
See af71c3969

**Comment by kyrsjo** [comment]
Note that "check_extras", which was added for FMA, could probably help here. However all our tests expects the results to be completely reproducible, which probably won't happen with collimation as long as they don't use CRLIBM etc.

**Comment by vkbo** [comment]
What is this issue about? It's rather cryptic.

There is now a number of tests with collimation, so can this issue be closed?

**Comment by rdemaria** [comment]
Do we have a collimation test?

**Comment by vkbo** [comment]
We have 15 at the moment.

**Comment by rdemaria** [comment]
I think we can close then, the issue was only for missing tests if I remember correctly
