### ISSUE TITLE
Allocate big arrays with the minimum number of slot (particle, number of elements) 

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#250]

**Comment by kyrsjo** [comment]
Maybe make this part of the daten module?

**Comment by JamesMolson** [comment]
The fluka coupling needs nele increasing, so it would be good to attack this issue.

The alternative is extra layers of +if / +ei statements.

everything that touches

- nele
- nblo
- nblz
- nzfz
- npart

probably should be hit with the allocate hammer.

**Comment by amereghe** [comment]
for info: for the coupling, the standard settings are:
```
+if .not.bignblz
      parameter(nele=6000,nblo=2500,nper=2,nelb=140,nblz=50000,         &
     &nzfz = 500000,mmul = 20)
+ei
```

**Comment by rdemaria** [comment]
Is it technically possible to increase dynamically the array size?

**Comment by amereghe** [comment]
in the ```mod_fluka.f90``` module we allocate some arrays based on parameters passed through the TCP/IP, so it is technically feasible

**Comment by kyrsjo** [comment]
We actually use several dynamic arrays in SixTrack - take for example DYNK, which is now completely dynamic, and parts of NAFF which also uses ALLOCATE. DATAMODS is basically just one big ALLOCATE.

In SixTrackV_dev I am slowly making some of the main +cd blocks into modules, which will make it possible to make the arrays allocatable. The question is rather *when* to allocate them, this will require some rethinking of DATEN, as the array sizes will depend on how much we read from there - however something similar to what @vkbo did in DYNK (basically implementing C++ vectors) may be one good option.

I'm getting there...

**Comment by rdemaria** [comment]
Did @vkbo <https://github.com/vkbo> use move_alloc or  something different?
Ideally a "c++ vector"-like is the correct data structure, I am wondering
if fortran allows it without rewriting many things.

**Comment by kyrsjo** [comment]
Move_alloc would have been an improvement - the current implementation is just copying the data off into a temp array, deallocating and re-allocating the main array (with a bigger size), then copying the data back and dumping the temp array.

I'll use that for my developments! For DYNK it would be a good idea to look at too, however I doubt that it is a big problem for runtime.

Thanks for the tip!

**Comment by JamesMolson** [comment]
Pretty much done for nele now.

**Comment by vkbo** [comment]
Completed for nblo, nblz and nzfz in #516

**Comment by kyrsjo** [comment]
Done!
