### ISSUE TITLE
Include cern.ch/sixtrack website sources in the github repository

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#255]

**Comment by kyrsjo** [comment]
Maybe as a separate repository under the SixTrack organization?

**Comment by kyrsjo** [comment]
We should also remove the CERN logo from this repository, or at least figure out how to make it work again; the image disappeared from the display of readme.md https://github.com/SixTrack/SixTrack/blob/master/README.md recently.

**Comment by JamesMolson** [comment]
See the bottom of this https://help.github.com/articles/about-readmes/

Just need to change the tag really (I think).

**Comment by rdemaria** [comment]
done in https://github.com/SixTrack/sixtrackweb
