### ISSUE TITLE
Bug in Beam-Beam inverse boost

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#260]
Wrong code

    *FOX    TRACK(2)=(TRACK(2)+CALPHA*SPHI*H1)*CPHI ;
    *FOX    TRACK(4)=(TRACK(4)+SALPHA*SPHI*H1)*CPHI ;

Fixed code

    *FOX    TRACK(2)=(TRACK(2)*CPHI+CALPHA*TPHI*H1) ;
    *FOX    TRACK(4)=(TRACK(4)*CPHI+SALPHA*TPHI*H1) ;

See eq. 2.39 in https://cds.cern.ch/record/425950/files/lhc-project-report-369.pdf. The code is supposed to invert the equation for px and py. 

Reported by Giovanni Iadarola @giadarol

**Comment by rdemaria** [comment]
One missing test, see comments in #261

**Comment by kyrsjo** [comment]
Let's reduce the size of the singletrackfile.dat in that test - curently it's a 90MB binary file :/
