### ISSUE TITLE
DUMP bug: ghost particles

### ISSUE THREAD

**Issue by KFubuki** [SixTrack/SixTrack#27]
Looking at the output file of the DUMP block, we can observe that there are some lines with the same particle ID, s position and turn, but displaying different coordinates (see image attached). This looks like a bug, since the position of a certain particle at a certain moment should be unique. 

The input files to recreate the simulation can be found here: https://drive.google.com/folderview?id=0B87GPcovg_nROHpXMjFwckVXaVk&usp=sharing

![dump](https://cloud.githubusercontent.com/assets/6048020/10972561/12739ba8-83da-11e5-8497-753ac7f1ed5f.png)

**Comment by KFubuki** [comment]
The dump file in question can be found here: https://drive.google.com/file/d/0B87GPcovg_nRU19xT0V2b2dQOUE/view?usp=sharing

**Comment by kyrsjo** [comment]
Thank you. Could you please specify which SixTrack version you were using?

**Comment by KFubuki** [comment]
data version /'4.5.28'/
      data moddate /'26.08.2015'/

**Comment by kyrsjo** [comment]
Observations, using https://github.com/kyrsjo/SixTrack/commit/92a851419364beb073250dbfe745cc77bcea5f41 :

Sample 1: No repetition
Sample 2: Repeat the last particle (#128) 1x every turn
Sample 3: Same as sample 2 (#192)
Sample 4: Last particle (#256) repeated 2x
Sample 5-24: Same as sample 4
Sample 25: Last particle (#1600) repeated 3x
Sample 26&27: Same as sample 25
Sample 28: Last particle (#1792) repeated 4x
Sample 29: Last particle (#1856) repeated 5x
Sample 30: Last particle (#1920) repeated 7x
Sample 31-36: Same as sample 31
Sample 37: Last particle (#2368) repeated 8x
Sample 38-41: Same as 37
Sample 42: Last particle (#2668) repeated 9x

Etc.

**Comment by kyrsjo** [comment]
More observations:
- The DUMP happens in as the first thing (on a marker) in IP1, and if a particle was lost in the previous turn, it is missing in the next turn.
- npart is only initialized at the beginning of trauthin(), NOT when copying the next batch of particles into the tracking arrays

Particle losses:
Sample 1: 1 particle (turn 49)
Sample 3: 1 particle
etc.

**Comment by kyrsjo** [comment]
Fixed in https://github.com/kyrsjo/SixTrack/commit/f6dbf662ae3e016aaf514437cf80f04f58e03537
