### ISSUE TITLE
FMA: Get different normalization matrix

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#299]

**Comment by kyrsjo** [comment]
Depending and mostly done in #301; only change in FMA should be to allow 4D.

**Comment by kyrsjo** [comment]
This may solve mfittere#12 mfittere#13 mfittere#14 mfittere#16

**Comment by kyrsjo** [comment]
Transferring information from comment by @mfittere in #301:

> common block:
>`+ca commonta`

**Comment by vkbo** [comment]
This is very cryptic and incomplete. Can @kyrsjo elaborate or possibly close if no longer relevant?

**Comment by kyrsjo** [comment]
After a bit of thinking, I think that I realize what is going on: When running 4D tracking with momentum scan, the TAS matrix is wrong for most of the particles, and the computed tunes are wrong.

As far as I remember, we don't allow that anymore, in which case the issue is moot and can be closed. Sorry about the poor description, it was written in the context of an ongoing discussion that ended.

**Comment by kyrsjo** [comment]
After a quick discussion with @vkbo : Momentum scan with 4D was removed in #804. So this is no longer an issue. Closed.
