### ISSUE TITLE
ZIPF: writing of output file comes too early in the CR version

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#307]
Currently, the end of `program sixtrack` looks like this:
```
      call closeUnits

      if (zipf_numfiles.gt.0) then
         call zipf
      endif

!     We're done in maincr, no error :)
+if cr
      call abend('                                                  ')
+ei
+if .not.cr
      stop
```

This means that when we are in the CR version, `subroutine zipf` is called before the final flushing of stdout etc. in `subroutine abend`.

This should be fixed - zipf should be the very last thing to happen. Furthermore, zipf should *probably* only be called if there was no error.

**Comment by rdemaria** [comment]
Not sure if don't want to zip results in case of error. It could still be useful for debugging, in particular when fort.6 is requested.

**Comment by kyrsjo** [comment]
Good point - however we definitively don't want them in case of error in reading the ZIPF block in fort.3. Another problem is that normally we only call `closeunits` just before calling `abend` at the end of the program -- however it is not called when exiting through `prror`.

FYI if there is an error in zipf itself, we'll just write to stderr in the C code and exit, abend is never called.

**Comment by vkbo** [comment]
This issue is addressed by:
* All files now being flushed before the HASH module, which comes just before ZIPF.
* ZIPF can't really be moved further down the pipeline. doZip doesn't call prror however, so if the zipping fails, SixTrack should continue to bend and return the error report if running on BOINC.
