### ISSUE TITLE
Crab cavities are not symplectic

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#309]
As reported by Frank and @androula :

> I had a look with Androula at linear optics of the SPS
> with and without crab cavities.
> 
> Fortunately, SixTrack writes out the deviation from the
> symplectic condition:
> 
> without:  ~1e-12
> with     :   ~1e-5
> 
> and there is exactly one term and its symmetric partner that
> are about ±1e-5.
> 
> Please keep in mind that ~1e-12 of deviation is purely
> numerical. This I have verified numerous times by redoing
> the analysis by going to 4-fold precision where the same
> lattice gives ~1e-38.
> 
> If confirmed with a toy model a deviation of ~1e-5 is
> clearly a sign of lack of symplectity! Maybe it is just a bad
> set-up of the FOXY part or it is truly a inconsistent
> implementation.
> 
> I think this might need a crash program to investigate the
> cause and mitigation of this potential problem. At this point
> I would NOT trust long-term simulations including crab
> cavities.
> 

See also issue #5

**Comment by androula** [comment]
All relevant files in 
[symplecticityChecks.zip](https://github.com/SixTrack/SixTrack/files/1237547/symplecticityChecks.zip)

and under

/afs/cern.ch/user/a/aalekou/public/symplecticityChecks

**Comment by kyrsjo** [comment]
Uh, that .zip is empty... You also wrote something in an email about how it was different in the SPS and LHC - could you please post that here too?

**Comment by androula** [comment]
I made a test-case with SPS@7TeV and SPS@55GeV. 

noCC_7TeV:       deviation for symplecticity    2.8569739167019878E-012
withCC_7TeV:     deviation for symplecticity    3.8043642310487249E-012
withCC_55GeV:  deviation for symplecticity    5.8273843685283981E-006

[symplecticityChecks.tar.gz](https://github.com/SixTrack/SixTrack/files/1238526/symplecticityChecks.tar.gz)

**Comment by rdemaria** [comment]
Should be fixed in dev
