### ISSUE TITLE
bignblz and collimation

### ISSUE THREAD

**Issue by JamesMolson** [SixTrack/SixTrack#31]
In order to use the FCC lattice, one needs to enable the bignblz option in order to increase nblz and friends.

Currently there is no way to increase nblz and have collimation enabled in the configuration.
There are no if statements to increase nblz if both the collimation and bignblz flags are enabled. One must manually edit the source code each time a new build is made.

**Comment by kyrsjo** [comment]
Hi James,
could you please upload an example fort.2 and fort.3 (etc.) for me to check? Just name them "fort.2.txt" (etc.) and drag them into the comment window.

I'll try to look at it tomorrow.
Thanks!

Cheers,
Kyrre

**Comment by kyrsjo** [comment]
Looking at sixtrack.s, it seems that this (in the PARPRO block) is the limiting factor:
> +if .not.collimat
> +if bignblz
>       parameter(nele=1200,nblo=600,nper=16,nelb=140,nblz=200000,        &
>      &nzfz = 300000,mmul = 20)
> +ei
> +if .not.bignblz
>       parameter(nele=1200,nblo=600,nper=16,nelb=140,nblz=20000,         &
>      &nzfz = 300000,mmul = 20)
> +ei
> +ei
> +if collimat
> +if beamgas
>       parameter(nele=50000,nblo=10000,nper=16,nelb=140,nblz=200000,     &
>      &nzfz = 300000,mmul = 11)
> +ei
> +if .not.beamgas
>       parameter(nele=5000,nblo=400,nper=16,nelb=140,nblz=15000,         &
>      &nzfz = 300000,mmul = 11)
> +ei
> +ei

i.e. the bignblz option is explicitly deactivated for the collimation version. Do you have any idea why? The nblz is also changed by "beamcas", so it does not seem like changing nblz is inheritly incompatible with collimat. To me, it seems like an oversight.

I'll just add in the if and commit it to a new branch for testing.

**Comment by JamesMolson** [comment]
[fort.2.txt](https://github.com/SixTrack/SixTrack/files/64023/fort.2.txt)
[fort.3.txt](https://github.com/SixTrack/SixTrack/files/64024/fort.3.txt)
[FCC_col.data.txt](https://github.com/SixTrack/SixTrack/files/64025/FCC_col.data.txt)


Those files should just work (In theory).

**Comment by JamesMolson** [comment]
Your fix seems to work for me without problems. There has been mention of the nblz parameter requiring a further increase in general (to 400k) by Barbara Dalena for the fcc but I'm not sure exactly why.

For future optics reference: 
Current "release" version - no RF /afs/cern.ch/eng/fcc/hh/LATTICE_V5/fcc_ring_roundracetrack_lhc_99.97

"Testing version" - has RF /afs/cern.ch/user/d/dalena/public/fcc/optics/

**Comment by kyrsjo** [comment]
(this was originally posted to issue #30 by mistake)

@JamesMolson Could you please test this version? It should be fixed there.
https://github.com/kyrsjo/SixTrack/commit/72ec7447840772faca1123e085a1ff5632ac11ea

@rbruce1 Do you see any problems with this fix? I.e. are there anything in collimat which is hardcoded to expect 15000 elements max? I don't have any testcase...

**Comment by kyrsjo** [comment]
James: Great, and thanks for the references! Sorry about the issue number confusion, I ended up having quite a few of them open at the same time.

Everything is still in a separate branch which will not be merged until next year, so I don't see any reason why we cannot increase nblz (for both the standard bignblz and the collimation+bignblz version) to whatever is needed.

**Comment by JamesMolson** [comment]
Thanks, I think the same would be needed for the nzfz paramter too from what I've been told.

**Comment by kyrsjo** [comment]
I'll look into that... It would be useful to run the example in valgrind to see that we don't have any silent memory corruption, which may cause invalid results.

**Comment by kyrsjo** [comment]
Re nzfz: This is used to size the gaussian random vectors zfz(nzfz) and zfz35(nzfz), which is used for randomized magnet strength. This is found many places. What would be a reasonable value for it, if bignblz is true?

Also, is there any check that this array is not exhausted, i.e. that izu < nzfz after initialization? Or will it just keep on gobbling random values from memory until the program (if we are lucky) crashes or (less lucky) produces very crazy results?

**Comment by rdemaria** [comment]
I would maintain a new flag and executable to be distinguish by bignlz because the memory footprint is very large

**Comment by kyrsjo** [comment]
So... "hugenblz"?

**Comment by kyrsjo** [comment]
Option hugenblz added; 400k elements. I did not change nzfz (for any of the versions) since I don't know what the value should be.

https://github.com/kyrsjo/SixTrack/commit/839d27af56487e90474f256346676e6926c6c58c
