### ISSUE TITLE
Build failure with debug flag enabled

### ISSUE THREAD

**Issue by JamesMolson** [SixTrack/SixTrack#32]
On fedora 23

$ gfortran --version
GNU Fortran (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)

Using:
./make_six gfortran debug

eventually gives:

Setting up for Windows (as well)

gfortran -c -frecord-marker=4 -O4 -m32 -g -fno-second-underscore -funroll-loops -mfpmath=sse -msse2 track.f
gfortran -c -frecord-marker=4 -O4 -m32 -g -fno-second-underscore -funroll-loops -mfpmath=sse -msse2 sixve.f
sixve.f:34798:31:

       endfile (100,iostat=ierro)
                               1
Error: Symbol ‘ierro’ at (1) has no IMPLICIT type
Makefile:17: recipe for target 'sixve.o' failed
make: *** [sixve.o] Error 1
       
./make_six : 
tried to build SixTrack_4529_cernlib_crlibm_gfortran_debug_O4 in the directory with the same name.

The following selections are ON  : tilt tracking fast crlibm cernlib gfortran debug
The following selections are OFF : api naglib da collimat cpss boinc cr nagfor pgf90 g95 bpm beamgas bnlelens bignblz hdf5 ifort fio SSE lf95

It appears to have failed!!!

Without "debug" sixtrack builds correctly.

**Comment by kyrsjo** [comment]
Hi James,
the debug flag is currently not really used, so I'm considering to close this one as wontfix. @rdemaria ?
