### ISSUE TITLE
ASTUCE +if flag definitions are very stupid

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#323]
Currently, if a flag is used anywhere, including inside a `+ca` included block in a file, the build system must handle it as such:
* The ast mask file MUST contain ALL relevant flags
* The CMakeLists removes the deactivated flags
* Astuce then processes the modified mask file.

The problem is that if a flag is forgotten in the ast mask file, the flag is just not enabled IN THAT .f(90) FILE. There is no warning or automatic check for this very easy mistake.

Therefore, I propose the following change:
Have CMakeLists know about ALL the flags, then remove the irrelevant ones, then patch ALL relevant flags into ALL ast mask files. Unused flags doesn't matter; missing ones do (argh. This explains why I tought HUGENPART was broken).

**Comment by vkbo** [comment]
All +ifs can now in principle be replaced by #ifdef, as long as they are defined properly in cmake. This issue should no longer be relevant.
