### ISSUE TITLE
Auto-assignment of output unit numbers

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#34]
In many parts of SixTrack, output to (or input from) named files, their number and filename specified directly or implicitly through input files, are required. This means that it is often up to the user to specify the fortran file unit number.

This could be avoided if
1. There was a "known safe" range of unit numbers to use
2. There was a mechanism in sixtrack to automatically allocate one of these safe unit numbers, keeping track of which units have already been allocated, and which units are currently free.

**Comment by amereghe** [comment]
I think that a middle step in this direction could be the creation of one common (or more) which parametrises official units (e.g. "lunout" could store the main output unit of 6T), thus blocking unit numbers to the users (i.e. the users should not use them for their own I/O).

**Comment by kyrsjo** [comment]
The real problem is when you have user-specified input/output files, such as for DUMP and DYNK. Output files are especially problematic, since they need to be kept open.

A simple way to implement this would be to have an array of ~1000 booleans, all initialized to false. Each of these bools would correspond to one unit number, "false" meaning the corresponding unit number is free, and "true" meaning that it is free. This array could then be accessed using two subroutines: ```requestUnit(int returnUnit)``` and ```releaseUnit(int unitToRelease```. These would allocate a unit from the pool (and mark it as "taken"), and release a unit from the pool (and mark it as free). Additionally, it could check that the unit is not already in use before allocating it (exiting with an error if it is), and check that it has actually been freed (the file is closed) before accepting a release (exiting with an error if not).

This should be very easy to implement, if we can find a "fore-sure safe" unit range.

**Comment by kyrsjo** [comment]
But one releated thing to what you are saying: An official list of unit numbers (which is more up2date than the manual) would certainly be a great thing. Especially if we could use "lout" instead of "*" in the non-cr version (it would need to have a different value); I'm fed up with having to type in every error message twice!

**Comment by kyrsjo** [comment]
LOUT everywhere is done in Pull request #233 !

**Comment by JamesMolson** [comment]
Auto assignment via #427 and #430 


Needs to be applied to most of the code

**Comment by rdemaria** [comment]
We close the issue since, the module is used for everything but the standard fort.<90 files. The module does automatic closing of unit till 999.
