### ISSUE TITLE
Inactive flag `rvet`

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#366]
The flag `rvet` is used several places (including common block `\main1\`, but is not defined in any of the (old) .ast files, meaning it is always inactive.

**Comment by rdemaria** [comment]
any idea for what is for?

**Comment by kyrsjo** [comment]
I tried asking Frank back in May 2016, however I did not get an answer.

**Comment by rdemaria** [comment]
Any hint from the code?

**Comment by rdemaria** [comment]
rvet(j) substitutes (one-rvv(j))*c1e3 in drift in thick tracking for the sigma update and similarly other thick maps. It looks like an optimization to avoid a recalculation of a term. We should see if it is the case by testing a thick lattice with or without the option rvet.

**Comment by vkbo** [comment]
The rvet flag and the code wrapped in it has been removed on sight, and should now be gone everywhere.
