### ISSUE TITLE
rounding selection on mathlib_bouncer

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#369]
Added mathlib_bouncer module, which removes the necessity of writing almost every mathematical expression twice -- Mostly done, but missing choice between round up / down / nearest / zero

**Comment by rdemaria** [comment]
waiting for new crlibm

**Comment by kyrsjo** [comment]
We don't need to wait for the new CRLIBM for this?

Also, we should probably set the FPU rounding mode...

**Comment by rdemaria** [comment]
We need nearest for sure otherwise we generate radiation damping or quantum excitation like noise...

**Comment by JamesMolson** [comment]
Done in #526 and #527
