### ISSUE TITLE
Modules for the global variables, dynamic array allocation ala DYNK

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#372]
Not sure this is blocking for merging 5.0, adding to 5.1

**Comment by rdemaria** [comment]
splitting done, dynamic allocation to be done

**Comment by kyrsjo** [comment]
Some of the modules for global variables were done in PR #387. Still a few to go, especially the common arrays for collimation needs to be stuffed into the collimation module and taken out of `sixtrack.s90`!

**Comment by JamesMolson** [comment]
I would say it is done.

**Comment by kyrsjo** [comment]
I think this is done :D
