### ISSUE TITLE
Ion tracking merging.

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#376]
Needs to be done as quickly as possible, otherwise it will lost. Tentatively blocking v5.0 unless clear responsibility and time scale for merging.

**Comment by rdemaria** [comment]
Existing maps now compatible with proton maps in James's branch. However new maps, CR, fluka needs to be implemented. Post processing to be reviewed.

**Comment by rdemaria** [comment]
Fox part fixed in #447

**Comment by JamesMolson** [comment]
Done
