### ISSUE TITLE
Test wire_thck6d failing on MASTER

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#386]
It seems that the test "wire_thick6d" is failing in MASTER, at least with GCC 7.2.1.

**Comment by kyrsjo** [comment]
Why was this closed?

**Comment by rdemaria** [comment]
James told me he did not see it any longer. Can you still reproduce it?

**Comment by kyrsjo** [comment]
Hmm, GCC 7.2.1 would be my desktop.  I also cannot reproduce it now. What changed? Strange.
