### ISSUE TITLE
Fort.3 ZIPIT block for BOINC

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#39]
The block should contain a list of files to put in Sixout.zip. This would enable collimation etc. to run on BOINC. If no ZIPIT block present, we may want to have a "default list" of files? In case of no BOINC, the block shall not be valid (In DATEN, detect no BOINC flag and exit if ZIPIT block is present).

See: http://indico.cern.ch/event/476291/contribution/0/attachments/1209033/1762820/SixTrack_20160108.pptx

Assignments:
- @kyrsjo : DATEN modification and new global arrays
- @ericmcintosh / @kyrsjo : Update code to select the files to zip

**Comment by rdemaria** [comment]
We could also think to disentangle the boinc library which contains a zip library, with another external zip library like http://www.libarchive.org/ and have the feature implemented regardless on boinc.

**Comment by kyrsjo** [comment]
Moving discussion from email thread, in order to make the information more accessible:

LibArchive looks nice; another alternative is libzip; however I haven’t found any Fortran interface for it so I may have to write some wrapper code. If I end up looking at writing a pile of wrappers, I’ll contact the authors (tk PIGTAIL giga DOT or DOT at and dillo ÆTT nih DOT at) first in case someone has done this before (not unlikely) but not published it anywhere easily found from Google. If we do write a wrapper, I would also find it useful to actually distribute them, separately from SixTrack.

It seems that BOINC uses some version of info-zip to do it’s zipping. I looked at that, however they only distribute binaries (i.e. “zip” and “unzip” commands) and the sources for that, so some brain surgery would be needed. They released the compression library as zlib, which was then built on to make libzip.

It also seems that the BOINC client can be configured to do “all the work”, possibly making zip support in SixTrack redundant? https://boinc.berkeley.edu/trac/wiki/FileCompression

**Comment by ericmcintosh** [comment]
Hi Kyrre, look forward to discussing this tomorrow.
I am a bit familiar with the BOINC stuff which I am using.
However I think your provision of a Fortran wrapper is
a good idea, rather easy to do as well.

I must also say I don't think we should be doing this in
SixTrack; it should be done in a script or .bat file.
Lots to talk over with you.     Eric.

**Comment by kyrsjo** [comment]
I thought having it built into the binary would be a requirement for running it on BOINC?

We'll talk to tomorrow.

**Comment by rdemaria** [comment]
Users need to choose the files to be returned after a sixtrack simulation
from a batch service depending on the study, be LSF, Boinc or something
else in future. I think it is better to establish a simple interface for
any batch service (e.g. shipping a zip and returning a zip), and give user
control in fort.3. Since we have already a zipping facility in sixtrack, I
think it is better to make it a standard feature in the main sixtrack.

What do you think?

**Comment by kyrsjo** [comment]
Agreed with Riccardo. I'm looking forward to discussing how the zipping is currently done from BOINC.

Would adding this zip functionality mean that the BOINC version would be the same as the standard CR version?

Cheers,
Kyrre

**Comment by ericmcintosh** [comment]
Hi Kyrre, didn't make it today. Will be in tomorrow
afternoon (after the open air pool I hope :-).

The NON-BOINC/LSF SixTrack does all zipping in the batch script.

BOINC version (not yet released) in my /afs/cern.ch/user/m/mcintosh/scratch1/SixTracko0

         call boinc_unzip()

to get the input files, C/R files etc as we may be restarting.

SixTrack BOINC does a call boinc_zipitall() at end to zip everything.

The boinc_unzip/boinc_zipitall are Fortran interfaces via an Igor routine
to the released BOINC zip library.

Eric.

**Comment by kyrsjo** [comment]
Fortran/c interface demo to libarchive:
https://github.com/kyrsjo/fortran_examples/tree/master/linkingC/libarchiveTest
Seems to work nicely. But the wrappers are ugly!

I'll start integrating it after @vikasnt has finished #37 , since I would need to modify the makefile and make_six quite a bit...

**Comment by kyrsjo** [comment]
Fixed in #173
