### ISSUE TITLE
Better error detection when reading fort.13

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#409]
When reading fort.13 (at least with CRLIBM), if the file is empty it will produce some cryptic errors. It would be good if (1) it checked that the file actually exists, and (2) it separated a premature EOF from other errors, and reported appropriately.

Furthermore, the particle number (which easily allows you to calculate the line number in the file) should probably be included in the error message.

**Comment by vkbo** [comment]
I will get to the parsing of fort.13 soon. I am implementing better error reporting on all input files, and will also add this for fort.13.

**Comment by kyrsjo** [comment]
@vkbo  is this one still valid, or can it be closed?

**Comment by vkbo** [comment]
I think so. It now report separate errors on:
* The open statement (could not open)
* Reading a specific pair from the file (reports which pair)
* If it cannot cast the value to float (also reports which pair)

I'll let you decide if that is sufficient.

**Comment by kyrsjo** [comment]
Very much sufficient! Close!
