### ISSUE TITLE
Typo in the single diffraction cross section for collimation

### ISSUE THREAD

**Issue by JamesMolson** [SixTrack/SixTrack#55]
See: http://cds.cern.ch/record/447077
Equation 3.11

The middle equation has b = 1/36 (106 - 17 M^2) b_el

The code in sixtrack has 1/26 instead of 1/36. This creates an unphysical break in the differential cross section.

The offending bit of code is currently at line 63542 in sixtrack.s
`              elseif (( xm2 .ge. 2.d0 ).and. ( xm2 .le. 5.d0 )) then`
`!hr09           bsd = (106.d0-17.d0*xm2) *  bpp / 26.d0`
`                bsd = ((106.d0-17.d0*xm2) *  bpp )/ 26.d0                !hr09`

The `bsd = ((106.d0-17.d0*xm2) * bpp )/ 26.d0 !hr09`
should be

`bsd = ((106.d0-17.d0*xm2) * bpp )/ 36.d0 !hr09`

**Comment by JamesMolson** [comment]
This is what I spoke to @rbruce1 about last week.

**Comment by rbruce1** [comment]
thanks James - correct. It's a change of 1 digit. It's probably not worth 
creating a fork just for this, but it would be great if we could have this fix 
in the next version.

**Comment by rdemaria** [comment]
Can you submit a pull request with the fix?

**Comment by JamesMolson** [comment]
Done.

**Comment by kyrsjo** [comment]
It is #56
