### ISSUE TITLE
add dynamic effect on multipole (type 11)

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#568]
Multipole effect are calculated using

B(n) = k(N) b(n)
A(n) = k(N) a(n)

where N is the order of main field k(N) set in fort.2, n is the order of the multipole kick set as relative strength a(n) or b(n) in fort.16 and A(n), B(n) is the absolute kick (stored in the array `aaiv` and `bbiv`) and used in tracking code.

Users may want to:
1) change k(N) and having all the B(n), A(n) updated (e.g. for power converter ripple studies)
2) change a specific b(n) (e.g. for decay and snapback studies, former TIME compilation flag)
3) or change directly A(n) or B(n) for other studies.

**Comment by tpersson** [comment]
I don't think that it is correct that the the main field from fort.2 is used as the relative strength. Instead there is a kind of fictive field strength defined in fort.3 that seems to be the scaling. http://sixtrack.web.cern.ch/SixTrack/docs/user_full/manual.php#Ch4.S1.p1

This is also what I see in tests and when I look into the code..

**Comment by rdemaria** [comment]
Correct, the relative scaling is done with the value in fort.3 (which for dipoles has even the opposite sign...)

**Comment by tpersson** [comment]
This was implemented in  #663 .
