### ISSUE TITLE
Input checking when reading fort.13

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#582]
Following the discussion during the presentation of Joel, a few checks should be added at the end of reading fort.13:
 * Check that momentum and energy of each particle is consistent within some error, if not print an error and crash
 * Check that the energy of the machine is consistent to the one set in the INIT block, if not crash (@rdemaria may comment this out to bypass a certain other bug).

**Comment by kyrsjo** [comment]
Note that this is not the same as #409

**Comment by kyrsjo** [comment]
@jodander

**Comment by vkbo** [comment]
This was fixed in PR #690. Particle energy is now recalculated from momentum.
