### ISSUE TITLE
Update particle population through a pipe

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#59]
In order to make it possible to run (for example) single-cavity collective effects simulations with multiple bunches, it is necessary to (1) send the current particle population to an external program, and (2) receive an updated particle population, possibly replacing the current population if a second bunch is to be loaded.

I am however not sure how this would interact with collimation...

The primary idea for implementation is to communicate the particles via a set of pipes. It would be best if the tracking variables particles are loaded/stored without converting to ASCII.

This module would be configured from a new block in fort.3 (`PIPE` maybe?), giving the names of the input/output FIFOs and possibly the element to use (or else just use tracking starting point).

**Comment by amereghe** [comment]
Hi Kyrre! This is what the Fluka-SixTrack coupling does...

**Comment by amereghe** [comment]
I mean... the communication functionality

**Comment by kyrsjo** [comment]
The work-in progress branch: https://github.com/kyrsjo/SixTrack/tree/BDEX

Related: DYNK-PIPE functionality: https://github.com/kyrsjo/SixTrack/tree/DYNK-PIPEFUN which is 90% done.

**Comment by rdemaria** [comment]
@kyrsjo, can we close this?

**Comment by rdemaria** [comment]
Kyrre said yes, closing.
