### ISSUE TITLE
Collimation block input checking: Number of packages

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#6]
Problem: The collimation block maximally accepts 200 (?) packages of 64 particles each. However, if the user tries to ask for more packages, it tries to do so and ends up corrupting the memory.

Solution: Check that the input is valid, stop with an error message if it is not.

**Comment by KFubuki** [comment]
100 packages! (AFAIK)

**Comment by kyrsjo** [comment]
Variables:
* # packages: nloop; set in COLL block parsing in daten/fort.3
* # particles: mynp = nloop*napx, set in trauthin, read from TRAC block parsing in daten/fort.3
* Particle arrays: myx, myxp, myy, myyp; All installed into tracking arrays (after converting to mm/mrad and adding closed orbit) in trauthin
* If bnlelens, myx etc. are defined in block rhicelens, length "npart" (64)
* Otherwise, defined in block "dbcommon", length maxn (defined in block collpara, default length 20000)

Strangeness: 
- If particle arrays have length 20k, 64 particles per package, then expect 315.5 packages max. However, it breaks earlier -> There must be some other limitation.

Other strange thing: Subroutine "macedis_coll" EXPLICITLY includes block collpara and also dbtrthin (mixed with i,j,mynp -- extra strange) and parts of dbcommon

**Comment by kyrsjo** [comment]
Strangeness: The parameter ```max_npart``` with default value 20000 (same as maxn), and some arrays which is sized to it (like x_out etc., found in block dbcollim) is never used? If so, these should be deleted (after it is confirmed to be safe). Comments @rbruce1 ?

**Comment by kyrsjo** [comment]
More strangeness: In the beginning of trauthin, napx = napx00, which is set equal to napx just after setting mynp=nloop*napx in trauthin. When this happens in trauthin, napx is already set to 64, ignoring the setting from fort.3. Very strange!

Also: bnlelens and collimat is not compatible. So at least we don't need to worry about that!

**Comment by kyrsjo** [comment]
Regarding the last comment: In daten, napx is the number of particle PAIRS. This is later multiplied by 2 in order to find the actual number of particles.

**Comment by kyrsjo** [comment]
Original issue fixed in: https://github.com/kyrsjo/SixTrack/commit/ebb0a641db3a0ed08cf1b1b38be82f63ff4bd06c

At the same, time a serious issue with particle initialization in COLLIMAT was detected and fixed (using ```-fcheck=bounds```). The max number of particles is now nmax=20000 => max 312 samples of 64 particles each.

**Comment by kyrsjo** [comment]
Unused variables deleted in https://github.com/kyrsjo/SixTrack/commit/1f4c66c8a1b7d5d38fc6cbee66c4a7ef637a8e97
