### ISSUE TITLE
DUMP and APERTURE

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#604]
While investigating a bug that I caused in Aperture (which disabled aperture), we stumbled over a possible bug in DUMP. In several tests (see for example `wire_thick6d`),  the particles were indicated as lost in turn X, while the dump continued to turn Y >> X. The singletrackfile was also unaffected by the change in the behaviour of the loss code, only fort.10 line 22 and 23 were affected.

**Comment by vkbo** [comment]
Is this still relevant, @amereghe ?

**Comment by amereghe** [comment]
Hi @vkbo ,
I have checked out the present master, and the concerned test looks fine - the issue seems gone. I will close the issue.
