### ISSUE TITLE
dump7_fma_thin4d and dump_all_highprec fails on Windows 7

### ISSUE THREAD

**Issue by vkbo** [SixTrack/SixTrack#637]
This has been the case for a while. Adding it here as a reminder that it needs looking into.

**Comment by kyrsjo** [comment]
Could you please post the test logs?

**Comment by rdemaria** [comment]
This is particularly bad for boinc studies...

**Comment by vkbo** [comment]
The problem is truncated dump format 3 and 8 files again.

**Comment by vkbo** [comment]
Possibly fixed by #648 and #645, but need to rebuild on Windows.

**Comment by vkbo** [comment]
This issue was resolved.
