### ISSUE TITLE
merlin, geant, beamgas build broken

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#643]

**Comment by vkbo** [comment]
Only for the SixDA executable. Fixed in PR #646 which turns of building of SixDA when any of these flags are on. This is presently also done for BOINC.

**Comment by vkbo** [comment]
There are more issues related to this. Re-opening.

**Comment by kyrsjo** [comment]
Beamgas was fixed in #657 right?

**Comment by vkbo** [comment]
Yes. Don't know the status of Geant4 though.

**Comment by vkbo** [comment]
This seems to be fixed with the new Geant4 implementation. Closing.

**Comment by JamesMolson** [comment]
um, not quite

**Comment by vkbo** [comment]
Does it not build?
