### ISSUE TITLE
crash with `WIRE` and `wire_flagco`

### ISSUE THREAD

**Issue by amereghe** [SixTrack/SixTrack#697]
case by Kyriakos

with the provided inputs, any 4.x version crashes with (or something similar):
```
At line 23720 of file /home/rdemaria/work/sixtrack/SixTrack/SixTrack/SixTrack_cmakesix_BUILD_TESTING_defaultcompiler_defaultbuildtype/sixve.f
Fortran runtime error: End of file
```

with:
```
    SixTrack :: Version 5.0.2 :: Released 23.08.2018
  ================================================================================================================================
    Git SHA Hash: fcf0e3a84439137c8ed0bc0ea93612a633678b3d
    Built With:   TILT FAST STF
    Start Time:   2018-11-09 16:30:07.052

------------------------------------------------------------------------------------------------------------------------------------
```
it exits with:
```
ERROR: in wirekick -  wire_flagco defined in WIRE block must be either 1 or -1!
bez(166) = ip_swc_l5.b1                                    
wire_flagco(166) = 0

    +++++++++++++++++++++++++++++
    +      ERROR DETECTED       +
    + RUN TERMINATED ABNORMALLY +
    +++++++++++++++++++++++++++++
STOP 1
```
but in the `fort.3` the wire has `flagco` to -1...

inputs in `lxplus` at `/afs/cern.ch/work/a/amereghe/public/4kyriakos`

**Comment by rdemaria** [comment]
latest master 773733423b17976c4ba90eb74ddecffa90b7c148 works

**Comment by rdemaria** [comment]
as well 5rc3, 5.0.1, 5.0.2

**Comment by vkbo** [comment]
The array is 0 by default, Is there a mismatch in element name here? Don't have easy access to the input files right now.

**Comment by tpersson** [comment]
Can we close this issue?

**Comment by tpersson** [comment]
This is not a problem in V.5. The feedback from the user:

_I do not use the 4.x version of SixTrack anymore. In the version I use now, 50101, everything looks normal.
If you are interested in some extra tests with the 4.x version and the wire please let me know if I can help._
