### ISSUE TITLE
expected number of files from `ZIPF` should not be in `CMakeLists.txt`

### ISSUE THREAD

**Issue by amereghe** [SixTrack/SixTrack#711]
When updating the `elensidealthin6d_DYNK_ZIPF`, the files in the `ZIPF` block must have also their counterpart among the `.canonical` ones. If the canonicals change, the number of files in the `ZIPF` block might change, leading the test to fail even if they are identical to the canonicals. Unless you change the `CMakeLists.txt` and re-build...

**Comment by vkbo** [comment]
Closing this as the entire logic here was deleted when libarchive was removed. The remaining issue regarding Sixout.zip is covered by issue #924.
