### ISSUE TITLE
Multiple defined labels in documentation

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#773]
When running the makefile in `doc/user_manual` on `master`:

At the bottom of the output:
```LaTeX Warning: There were multiply-defined labels.```

A bit higher up:
```LaTeX Warning: Label `tab:DYNK_SET' multiply defined.```

**Comment by kyrsjo** [comment]
Just saw: This table has suddenly been split into two tables? That's not necessary.

**Comment by kyrsjo** [comment]
Also, the ordering seems kindof random now? Why not order also the new elements by kz?

**Comment by kyrsjo** [comment]
Hello,
much better now! There is still something weird going on with that table tough - do we really need all the parbox'en? Also it is wider than the actual A4 page margins...

Don't know about the HTML part; after installing the LaTeXML `generateForWeb.sh` ran (as it also did, without any noticeble warnings, when the tool was not installed), but it's not clear to me where to find the HTML code. I found some `.php` files tough, and the `LaTeXML` seemed to be making mostly happy noises while parsing the LaTeX...

**Comment by tpersson** [comment]
Fixed in #782
