### ISSUE TITLE
Future ideas for FMA

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#79]
Ideas which were thrown around but never actually implemented in the PLATO FMA analysis merged in version 4.5.35:
- Use binary DUMP files ( #15 ) to increase accuracy / decrease filesize of readin/readback
- Implement Laskar method as is done in Lifetrack https://cdcvs.fnal.gov/redmine/projects/lifetrac/wiki/FMA_Analysis
- Use double precision in PLATO
- Optional extra input arguments for fine-tuning analyses

**Comment by kyrsjo** [comment]
FMA was merged: https://github.com/SixTrack/SixTrack/commit/d25f116dbdbf8da33678fdee13e36a100bc36d5f

**Comment by mfittere** [comment]
Comments/Extensions to list:

- Optional extra input arguments for fine-tuning analyses = additional input parameters to FMA analysis, e.g. windowing function used in FFT
- allow for different initial distribution of particles, e.g. rectangular grid as in LifeTrac
- add in fma_sixtrack output file:
    - min/max turn number used for calculating tune
    - normalisation flag 

 min/max turnnumber

**Comment by kyrsjo** [comment]
Issues on Miriam's tracker:
* https://github.com/mfittere/SixTrack/issues/12
* https://github.com/mfittere/SixTrack/issues/13
* https://github.com/mfittere/SixTrack/issues/14

**Comment by mfittere** [comment]
Another issue:
[https://github.com/mfittere/SixTrack/issues/16]

**Comment by kyrsjo** [comment]
Is FMA always rewriting the `NORM_dumpname` files? These can be huge; this is a performance issue. If we could avoid it, that would be useful...

**Comment by mfittere** [comment]
it shouldn't? Please check or I check later? the write() statement 
should just append to the file or what do you mean?

**Comment by kyrsjo** [comment]
What I mean is that if we can reuse a NORM_ file, why not do that? Why re-read the DUMP, recalculate, and re-write the NORM_dump if we can avoid it? I/O takes a lot of time. Having some sort of cache, where "if the file is already written then don't write it again", and maybe even "if the file is already loaded in memory, then don't read it again", would avoid that.

I saw it because for some reason, my SSD decided to be super-slow while running the fma test (maybe I should get around to enabling TRIM... I'm probably beating quite hard on the poor thing), and checking with `ls -l` in the folder it runs in while it ran, I saw that the size of the NORM files kept going to zero, then growing, then zero, then growing... etc.

It's just that if you have a lot of DUMP files and a lot of FMA analyses, you may spend more times reading and writing these files than tracking or actually FMA'ing...

**Comment by mfittere** [comment]
Hi Kyrre,

excellent idea! I think one would have maybe 10 FMA cases in a real run. 
I will put it on the issue tracker for the FMA in order to keep it in 
mind. If you feel like implementing it, I would be very happy :-).

Miriam

**Comment by kyrsjo** [comment]
I feel like reviewing a patch :)

While we're discussing input files... Are there any particular reasons why we need to do the "firstturn/lastturn" in DUMP instead of directly in FMA?

**Comment by mfittere** [comment]
:-). I don't see one at the moment. I mean what you need as steps is:
1) dump particle coordinates for t0 to t1 turns
2) normalize them
or
1') normalize coordinates
2') dump them

3) do the tune analysis (= FFT + fancy things) of particle amplitude 
from t0 to t1 turns

It proofed to be very useful to get the unnormalized and normalized 
particle coordinates (the *DUMP* and NORM_*) files for debugging, 
because this is not very robust at the moment.

Miriam

**Comment by kyrsjo** [comment]
Yes!

Could this work as well? :
1. Dump particle coordinates for t0 to t2 turns, write to file1
2. At the end of tracking, read file1, normalize, and write to file2
3. Do the tune analysis from t0 to t1 and t1 to t2, where t0<t1<t2, without re-writing the normalized dump file.

**Comment by mfittere** [comment]
yes! Note that you need one of those files per marker, e.g.
IP2 t0 t2 -> file0_1
IP4 t3 t5 -> file1_1
-> normalize -> file0_2, file1_2 -> analyze from t0 to t1 and t1 to t2, 
and from t3 to t4 and t4 to t5

Not that you can have many steps here.

What might become a problem: If a user wants to do e.g. this 
(unrealistic, but possible):
DUMP_1 1 1000
DUMP_2 999000. 1.e6
Then you suddenly dump one million turns into one file/one array.

Miriam

**Comment by kyrsjo** [comment]
Exactly, and this way you would remove the need for multiple markers in the same position. Well, except maybe for the issue you mention at the end.

But I don't understand why you need to store all the 1 million turns into one array - when you do the normalization, you can also read one line, normalize it, write it out, then move on to the next line etc. ...

**Comment by mfittere** [comment]
yep, you can do that. But you still need to store your initial 
coordinates (the dump* files) somewhere.

Miriam

**Comment by kyrsjo** [comment]
Why? During the conversion, you actually only need to store the line you're currently working on, and during the FFT you only need the turns you're actually working on. I see no reason why you can't selectively read only the data you need from the file, and only create the file when it doesn't already exist?

**Comment by mfittere** [comment]
which file now? The NORM* or the DUMP* file?
Miriam

**Comment by kyrsjo** [comment]
Closing as it is split into #299 #300 #301 #302 #303 #304 #305 #306
