### ISSUE TITLE
Floating point div0, tbetax = 0 for some elements

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#8]
Description as reported by Andrea Santamaria:
https://www.evernote.com/l/AHNAr9ej1jlK_rD0-TvprNn_bjbXfq7hJMY

Most likely, this is a bug in LINOPT.

**Comment by KFubuki** [comment]
A temporary solution seems to be removing the object **acnca.d5l4.b1** from the fort.2

**Comment by kyrsjo** [comment]
In the files attached to the Evernote note.

This object represents the kick from a 200 MHz RF cavity with zero voltage, which is then turned into a non-kick (identity transform) (ktrack=31) in preprocessing.

**Comment by kyrsjo** [comment]
A CollDB is also needed to run the simulation; this one will do:

[CollDB.ats.11t.b1.txt](https://github.com/SixTrack/SixTrack/files/81109/CollDB.ats.11t.b1.txt)

**Comment by kyrsjo** [comment]
The problem seems to be that in subroutine LINOPT, subroutine WRITELIN is not called for certain classes of elements, including cavities. This makes that torbx (etc) uninitialized for these elements.

However, in the tracking, if
```
(secondary(j).eq.1.or.tertiary(j).eq.2.or.other(j).eq.4)   &
     & .and.(xv(1,j).lt.99d0 .and. xv(2,j).lt.99d0)
```
it is still checked if the position (in sigma) is > sigsecut2, or if the square sum of the x- and y-position is > sigsecut3. It is then written to tracks.2.

The problem is that you can't calculate sigma without the betafunction, i.e.:
```(xv(1,j)*1d-3)**2 / (tbetax(ie)*myemitx0)```
(and similar for xv(2,j)) produces a div/0 error.

**Comment by kyrsjo** [comment]
Working through this, partly rewriting LINOPT...

Note that linopt has an argument dpp (deltaP/P), which is taken from the dpp of particle 1 in the INIT block. Setting this to nonzero would result in an off-momentum orbit and twiss.

We may want to investigate this closer, and add a check in collimat that this is actually identical to zero.

**Comment by kyrsjo** [comment]
Initial attempt at fixing:
https://github.com/kyrsjo/SixTrack/commit/f8f90fe9d3554db8431bf74fc5758eb5302a7c61

It changes a few things about how LINOPT works; especially it now only calls WRITELIN at the end of every block, not at every contained element -- This did not make sense with collimat (so maybe doing it for not-collimat would be OK). Furthermore, it calls writelin at ALL elements (at least for collimat), including disabled cavities, crabs etc.

Running the test suite now.

@rdemaria : Could we take a look together? There are also some strange interaction with the orbit correction block which I'm not really sure about, I suspect a bug...

**Comment by kyrsjo** [comment]
I tested the branch, it passes all SixTest tests.

However, I noticed one thing (both pre- and post-LINOPTFIX) when running a version compiled with the extra gfortran flags ```-ffpe-trap=invalid,zero,overflow,underflow -fcheck=all -O0 -g```: Test "bb" crashed with the following error message:

```Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
# 0  0x87A618F in _gfortran_backtrace
# 1  0x879015B in _gfortrani_backtrace_handler
# 2  0xF77E73FF
# 3  0x8639CD4 in damult_ at dabnews.f:1965 (discriminator 12)
# 4  0x8626949 in damul_ at dabnews.f:1914
# 5  0x850D605 in umlauda_ at sixvefox.f:4608 (discriminator 8)
# 6  0x8599CAD in clorda_ at sixvefox.f:11796
# 7  0x861F58B in mydaini_ at sixvefox.f:12054
# 8  0x82FDA92 in qmodda_ at sixve.f:21483
# 9  0x8488DA1 in maincr at sixve.f:7631```
(# and NUMBER separated by space to avoid GITHUB autoreferencing)

**Comment by kyrsjo** [comment]
After discussion with @rdemaria , I will:
 * Put back WRITELIN after elements inside BLOC - it doesn't really matter for collimat, and in the case of thick tracking the output may be wanted.
 * Add a "guard" logical to WRITELIN to disable CORRORB output (which depends on IX) for BLOCKs (and elements inside of blocks)

Then run tests & release 4.5.31!

Anything I forgot?

**Comment by kyrsjo** [comment]
Done:
https://github.com/kyrsjo/SixTrack/commit/a27a9e9a6760b07efdbed94fa250dc2a71570509
