### ISSUE TITLE
Segfault on missing elens block when elens in lattice

### ISSUE THREAD

**Issue by vkbo** [SixTrack/SixTrack#826]
If there are elements of type 29 in the single element list (at least with thick 6d), but no elens block in fort.3, SixTrack segfaults (with debug build). This should probably be caught before tracking.

Error: Fortran runtime error: Index '0' of dimension 1 of array 'elens_offset_x' below lower bound of 1

Can be reproduced by commenting out the elens block in test elensidealthck6d.

**Comment by amereghe** [comment]
thanks for signalling it.
yes there is no explicit check like this, as for the chebyshev maps - I am wondering what about other element types...

**Comment by vkbo** [comment]
There's a similar bug between SCATTER and DYNK as well. I'll get to it soon.
I think as a principle, SixTrack shouldn't segfault on erroneous user input, but it isn't always easy to catch these.

**Comment by amereghe** [comment]
agreed - I simply think that such a check does not exist at all.
I guess that the best thing to do is to have a subroutine called after daten (or anyway once input parsing is done) that performs the check.
I can draft it in the context of the issue on elens

**Comment by vkbo** [comment]
Agree. A few modules have `_postInput` routines that are either called when the block is closed, or after `ENDE`. I think that is a relatively clean approach.

**Comment by amereghe** [comment]
that's what I thought first - but I think it is better to have the search in a place only, with all concerned elements

**Comment by vkbo** [comment]
Hmm, I'm not sure I agree here. I think it's cleaner if each block solves its own dependencies within the corresponding module. We've been trying to keep block-specific code in their own modules, and not spread the code around. Since the dependency here is a bit more detailed than just the existence of other blocks, I think this is a better approach.

@kyrsjo ?

**Comment by amereghe** [comment]
I think that indeed what you want to spot is something missing in your blocks - so I think we should have an explicit loop on all SINGLE ELEMENTS, calling check functions specific to the element type.

It is fine with me to go with the `_postInput` subroutines - it is just less evident to new comers that those also check missing info from the user...

**Comment by vkbo** [comment]
Ah, I see. You want a loop that calls specific checking routines in feature modules that check dependencies on an element by element basis. That is very specific to this issue though, and in case of the DYNK-SCATTER case, becomes very convoluted.

**Comment by amereghe** [comment]
ok - for elenses and chebyshev, the check is already there, but in the `_parseInputDone` subroutines. I will move it to the `_postInput` subroutines

**Comment by vkbo** [comment]
Fixed in #833
