### ISSUE TITLE
SixTest run_pro should check that the test exists

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#85]
If one by mistake puts a wrong folder name in the `TESTS` variable before running run_pro, this is not discovered. I then copies nothing, then attempts to run SixTrack which predictably crashes.

If `run_pro` (and `run_kill`?) would check that the folder actually exist before trying to run a test, this would be better.

**Comment by kyrsjo** [comment]
Low priority, since we have ctest now. Let's close it when we finally remove SixTest.

**Comment by rdemaria** [comment]
Shall we close, since we have ctest?

**Comment by kyrsjo** [comment]
If SixTest is still there, close it since it relates to deleted code.
If SixTest is not still there, delete SixTest and close this one.

**Comment by JamesMolson** [comment]
These have all been deleted now, so closing.
