### ISSUE TITLE
Word missing in error message in DYNK FIR/IR

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#858]
If the number of lines in the file does not match the degree given in fort.3, an error message `ERROR FUN:FIR/IIR Unexpected when reading file '"//trim(dynk_cData(dynk_ncData))//"'"`

Three letters are missing here.

See #855

**Comment by vkbo** [comment]
This issue is as cryptic as the error message.

**Comment by kyrsjo** [comment]
Sorry, from #855 :

Unexpected what? Unexpected EOF it is. which is kind of critical, since this is an user-provided input file, and if I remember the code correctly, this is basically failing on the order of the filter set in fort.3 and the number of coefficients provided not matching.

As you said there, it is not necessarily an unexpected EOF, just that something went wrong with the file. Basically it did not manage to read all the requested lines from the file for some reason (which could be EOF).

I can make a PR to fix this and #857 once #855 is merged (it's a bit too close to your other changed lines for comfort wrt. merge conflicts to do right now).

**Comment by vkbo** [comment]
It is already fixed.
