### ISSUE TITLE
subroutine for readin with round_near

### ISSUE THREAD

**Issue by mfittere** [SixTrack/SixTrack#86]
for reading in floating point numbers, round_near is used by the `DYNK` and `ELEN` block. fround already presents a subroutine which only takes the field length and field as input, but it is  limited by the maximum number of fields:

```
      double precision function fround(errno,fields,f)
      implicit none
      integer maxf
      parameter (maxf=30)

```

If a field is then longer than 30 characters, this would result in a non-zero terminated string. As round_near assumes a zero-terminated string the readin becomes incorrect.

Task: rewrite fround without field limitation.

**Comment by rdemaria** [comment]
Will be handled by @vkbo when cleaning up dynk

**Comment by vkbo** [comment]
Done.
