### ISSUE TITLE
Error tests fail for C/R

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#860]
And are disabled in the CMakeLists without any explanation. #855

**Comment by vkbo** [comment]
They don't need to run for C/R.

**Comment by kyrsjo** [comment]
That's true, but at least put a short comment in the CMAKE to let other know why they are failing (stderr being jumbled / missing / has extra output and no point to change it since we can just as well test the same things in non-CR).

**Comment by vkbo** [comment]
Can you stop reopening issues while I am pushing the fixes.
