### ISSUE TITLE
Output unit 54 used two places

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#90]
It seems that the output unit number 54 is used two places: In the collimation version (controlled by parameter `outlun`) for the file `colltrack.out`, and also for the file `beambeamdist.dat` in `subroutine bnlrdis`. There is also a `fort.54` mentioned in `call boincrf('fort.54',filename)` followed by an `open(54, ...` statement in `+cd open` - however this seems to be wrapped in `+if bnlelens` (to be confirmed). There is also a `close(54)` in `subroutine closeUnits`, inside a `+if bnlelens/+ei` (confirmed).

**Comment by rdemaria** [comment]
It is not by chance as was done by the same person... Shall we investigate
further?

**Comment by kyrsjo** [comment]
Hmm, so maybe it isn't actually a bug? Just weird. Do you know who did the old bnlelens? I like Miriam's idea of making it a part of the new ELENS code, then cleaning out the old code. That would break some compatibility and invalidate some inputs, however I don't really consider it part of the "core tracking engine"...

**Comment by mfittere** [comment]
I would just drop the BNL people a mail and ask them about their 
opinion? Riccardo, you know who do best contact? Wolfram?

Cheers,
Miriam

**Comment by kyrsjo** [comment]
Agreed. But let's finish #81 first!

**Comment by mfittere** [comment]
of course :-).

**Comment by kyrsjo** [comment]
FMA is now merged; we should investigate further :)

**Comment by kyrsjo** [comment]
I guess if we go ahead and delete the bnlelens code as discussed in #140 , this can be closed?

**Comment by JamesMolson** [comment]
unit 99 is also used for betatron.dat and distsec AND orbitchecking.dat

**Comment by JamesMolson** [comment]
and 'dump' .....

**Comment by JamesMolson** [comment]
Fixed in #431
