### ISSUE TITLE
Missing element label/name in the apperture_losses.dat

### ISSUE THREAD

**Issue by agorzawski** [SixTrack/SixTrack#926]
In some cases, an empty label for the element appears in the apperture_losses.dat file.
Found while parsing the file 

See example run in the `/afs/cern.ch/user/a/agorzaws/public/local_TEST-AGAIN-NO_GEO_job_1/run_00001/aperture_losses.dat`

Already we had a first look with @amereghe. And we found that the missing element name belongs to the IDs pool that APER module adds after initial aperture check.

**Comment by amereghe** [comment]
Thanks, Arek, looking into this more in details right now

**Comment by vkbo** [comment]
Fixed in PR #928
