### ISSUE TITLE
SixTrack CR version has problems working with BTRFS file system

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#97]
It seems that when running the SixTest checks for the CR version on top of the BTRFS file system, something goes wrong. After running several tests, mkdir, touch etc. fails claiming that the disk is full until the machine is rebooted. Afterwards, files may be missing from the SixTest folder.

We should run a test on a different machine to see if this is a machine specific problem or a file system bug/limitation...

**Comment by rdemaria** [comment]
I can give you access to my machine where I have BTRFS...

**Comment by kyrsjo** [comment]
Given that the symptom is "machine useless until rebooted, nothing can be written to disk, possible file system corruption", I don't think you want that :)

I guess this is what virtual machines are for...

**Comment by JamesMolson** [comment]
I've had the same problem, its a btrfs issue. Do you have warnings about btrfs_free_reserved_data_space_noquota ?

**Comment by kyrsjo** [comment]
Hi James,

cool to hear! No, I didn't see any warnings, just that any command writing to the file system failed with a message that the disk is full. Nothing in dmesg either. Furthermore, all files (not folders) in the SixTest folder disappeared (everything else seems fine tough) - did this happen to you as well? 

I have a vague feeling that TRIM'ing the SSD on which the file system was residing did prolong the time before the problem appeared, i.e. before TRIM it crashed during the first 1-2 tests, while afterwards it ran through almost all, crashing on prob1.

The main suspect would be the way files are "restarted", i.e. by `rewind`ing, then `read`ing all records up the truncation point, and truncating by calling `endfile` then `backspace`. It would be interesting to write a short example program that causes the same crash, first in FORTRAN, then possibly in C.

Woho, kernel bug time :) Or maybe just misconfiguration of the FS...

**Comment by JamesMolson** [comment]
Hmm, well I've not got an SSD on this. On my other btrfs machine at home its raided and has never produced any issues. Which test triggers the badness for you? I'll see if it happens here and then go hunting for the problem.

**Comment by kyrsjo** [comment]
One thing that for sure provoked it was when I was basically settings `TESTS` = all the tests, running both normal+CR and STF+CR version and also the non-CR versions at the same time. After completing a few tests, it blew up. I've also seen it stop after only 1-2 tests, with a single CR executable (STF or not did not seem to make any difference).

**Comment by JamesMolson** [comment]
Running everything now, no issues at all so far. Have you seen:
https://btrfs.wiki.kernel.org/index.php/FAQ#Help.21_Btrfs_claims_I.27m_out_of_space.2C_but_it_looks_like_I_should_have_lots_left.21

**Comment by JamesMolson** [comment]
well I ran with everything in the readme selected: "The following test cases may be used (amongst others):
bnl exact crabamp javier thick4 lost tilt dipedge bb bb_ntwin1 notilt lostnotilt
lostevery s316 eric frs frs60 bbe51 bbe52 bbe571ib0 distance prob3 prob1 fma
elensidealthck4d elensidealthck6d elensidealthin4d elensidealthin6d.
"
And all the tests finished with no issues (that I can see).

**Comment by JamesMolson** [comment]
I suspect that somehow/somewhere this issue has gone away now? @kyrsjo ?

I've had no btrfs issues in quite some time now.

**Comment by kyrsjo** [comment]
The problem seems to have dissapeared by itself, so I'm going to close this. Probably a file system driver bug that was fixed?
