### ISSUE TITLE
make `NOFILE` in `DYNK` module the default behaviour

### ISSUE THREAD

**Issue by amereghe** [SixTrack/SixTrack#982]
When using `DYNK`, the `dynksets.dat` file is always written unless the user explicitly issue a `NOFILE` keyword in the `DYNK` block. It happened that on BOINC a series of dynked jobs was killed with error `EXIT_DISK_LIMIT_EXCEEDED`, since the `dynksets.dat`was growing too much - with 1e7 turns...

It would be great to change the user interface such that:
- `dynk_noDynkSets` is set to `.true.` by default;
- `dynk_noDynkSets` is set to `.false.` by a specific keyword (e.g. `DYNKSETS`);

**Comment by vkbo** [comment]
I think that's a good idea. In general, large files mainly used for debugging test setup should be off by default.

I can update the parsing for this.

**Comment by kyrsjo** [comment]
Yeah, agreed.

Hopefully whoever used DYNK for 1e7 turns also didn't use FUN FILE ...

**Comment by vkbo** [comment]
Solved in PR #992.
